const fs = require("fs");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const iconsDir = path.join(rootDir, "node_modules", "heroicons", "24", "outline");

const ICONS = {
  loader: "arrow-path",
  zap: "bolt",
  undo: "arrow-uturn-left",
  shieldCheck: "shield-check",
  alert: "exclamation-triangle",
  cog: "cog-6-tooth",
  chevron: "chevron-down",
  key: "key",
  eye: "eye",
  eyeOff: "eye-slash",
  cpu: "cpu-chip",
  trash: "trash",
};

const CUSTOM_ICONS = {
  // Pixel free icons by Streamline (CC BY 4.0) — https://creativecommons.org/licenses/by/4.0/
  smell: `<path d="M28.955 1.53h1.52V6.1h-1.52Z"/>
    <path d="M25.905 1.53h3.05V0H3.045v1.53H6.1V6.1H3.045v24.38h1.53V7.62h22.85v22.86h1.53V6.1h-3.05ZM10.665 6.1h-3.05V1.53h3.05Zm4.57 0H12.2V1.53h3.04Zm4.57 0h-3.04V1.53h3.04Zm4.58 0h-3.05V1.53h3.05ZM4.575 30.48h22.85V32H4.575Z"/>
    <path d="M24.385 15.24h1.52v1.53h-1.52Zm0 7.62h-1.53v-3.05h-1.52v-1.52h-3.05v-1.52h-1.52v-1.53h-1.53v-1.52h-1.52v1.52H12.2v3.05h1.52v1.52h3.05v1.53h-3.05v-1.53H12.2v-1.52h-1.53v1.52H9.145v3.05h-1.53v1.52H6.1v3.05h1.52v1.53h16.77v-1.53h1.52v-3.05h-1.52Zm-1.53 3.05H9.145v-1.53h13.71Zm0-9.14h1.53v1.52h-1.53Zm-1.52-1.53h1.52v1.53h-1.52Zm0-6.09h1.52v1.52h-1.52Zm-9.14 1.52h1.52v1.52h-1.52Zm-1.53 1.52h1.53v1.53h-1.53Zm-1.52-1.52h1.52v1.52h-1.52Zm-3.05 4.57h1.52v1.53h-1.52ZM1.525 1.53h1.52V6.1h-1.52Z"/>`,
};

function extractSource(name) {
  const file = path.join(iconsDir, `${name}.svg`);
  if (!fs.existsSync(file)) {
    throw new Error(`Heroicon not found: ${name}.svg`);
  }
  const raw = fs.readFileSync(file, "utf8");
  const inner = raw
    .replace(/<svg[^>]*>/i, "")
    .replace(/<\/svg>\s*$/i, "")
    .trim()
    .replace(/\s+(?:stroke|fill)="#[0-9A-Fa-f]{3,8}"/g, "")
    .replace(/\s*\n\s*/g, " ");
  return inner;
}

const customEntries = Object.entries(CUSTOM_ICONS).map(
  ([key, inner]) => `  ${key}: '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32" aria-hidden="true">${inner.replace(/\s*\n\s*/g, " ").replace(/\sfill="currentColor"/g, "")}</svg>'`
);

const heroiconEntries = Object.entries(ICONS).map(
  ([key, file]) => `  ${key}: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">${extractSource(file)}</svg>'`
);

const output = `// Generated by scripts/extract-icons.js.
// Heroicons (MIT) from the heroicons npm package; "smell" icon: Pixel free
// icons by Streamline (CC BY 4.0) — https://creativecommons.org/licenses/by/4.0/
// Do not edit by hand — run: npm run icons
window.BS_ICONS = {
${[...customEntries, ...heroiconEntries].join(",\n")}
};
`;

const dest = path.join(rootDir, "icons.js");
fs.writeFileSync(dest, output, "utf8");
console.log(`Generated icons.js (${Object.keys(CUSTOM_ICONS).length + Object.keys(ICONS).length} icons) → ${dest}`);