const fs = require("fs");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const iconsDir = path.join(rootDir, "node_modules", "heroicons", "24", "outline");

const ICONS = {
  smell: "signal",
  loader: "arrow-path",
  zap: "bolt",
  undo: "arrow-uturn-left",
  shieldCheck: "shield-check",
  alert: "exclamation-triangle",
  cog: "cog-6-tooth",
  chevron: "chevron-down",
  key: "key",
  eye: "eye",
  eyeOff: "eye-slash",
  cpu: "cpu-chip",
  trash: "trash",
};

function extractSource(name) {
  const file = path.join(iconsDir, `${name}.svg`);
  if (!fs.existsSync(file)) {
    throw new Error(`Heroicon not found: ${name}.svg`);
  }
  const raw = fs.readFileSync(file, "utf8");
  const inner = raw
    .replace(/<svg[^>]*>/i, "")
    .replace(/<\/svg>\s*$/i, "")
    .trim()
    .replace(/\s+(?:stroke|fill)="#[0-9A-Fa-f]{3,8}"/g, "")
    .replace(/\s*\n\s*/g, " ");
  return inner;
}

const entries = Object.entries(ICONS).map(
  ([key, file]) => `  ${key}: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">${extractSource(file)}</svg>'`
);

const output = `// Generated by scripts/extract-icons.js from the heroicons npm package (MIT).
// Do not edit by hand — run: npm run icons
window.BS_ICONS = {
${entries.join(",\n")}
};
`;

const dest = path.join(rootDir, "icons.js");
fs.writeFileSync(dest, output, "utf8");
console.log(`Generated icons.js (${Object.keys(ICONS).length} icons) → ${dest}`);